### ISSUE TITLE
Add to the TECHNICALDEBT.rst file the below . IDE (visual code) friendly API doc popup 

### ISSUE THREAD

**Issue by alanmehio** [Issamricin/dmc-view#102]
If we take [Pandas ](https://pandas.pydata.org/docs/)
we can see if we hover over a method in VS , it shows a popup with the method input and output parameters also at the bottom it shows the API doc explaining the method. 
This should be added to Technical Debt also or if you can fix it and improve the api docs ( you decide)

see example : 
`import pandas as pd

mydataset = {
    'cars': ["BMW", "Volvo","Ford"],
    'passing': [3,7,2]
}

myvar = pd.DataFrame(mydataset)
print(myvar)`

Try the above example in VS and  mouse hover over the method **DataFrame** above

**Comment by Issamricin** [comment]
So i have to add docstring into the methods of the compass.py ? if i add those the popup will work fine.
like in the cli.py file if we hover over the methods the popup works fine there.

i can fix it instead of adding it to the technical debt

**Comment by alanmehio** [comment]
Not sure. Please read the steps below:#
Down load the Pandas project first ( source code clone it from github)
Move to the file which contains the method mentioned above 
Try to find the API doc style ( google or numpy ...)
Learn about their API Documentation for the method, classes etc..
See their style and let me know first
This is to teach you how to look into existing open source project and learn from them 
Report back in an email your finding.
